# Rules for increase level building
parameters:
    buildings_rules:
        1:
            name: hunting_lodge
            gold: 50
            resources:
                24:
                    name: wood
                    quantity: 50
        2:
            name: vegetable_garden
            gold: 50
            resources:
                24:
                    name: wood
                    quantity: 60
        3:
            name: plantation
            gold: 70
            resources:
                24:
                    name: wood
                    quantity: 60
        4:
            name: bakery
            gold: 50
            resources:
                24:
                    name: wood
                    quantity: 50
        5:
            name: dairy_farm
            gold: 50
            resources:
                24:
                    name: wood
                    quantity: 60
        6:
            name: cheese_factory
            gold: 50
            resources:
                24:
                    name: wood
                    quantity: 50
                23:
                    name: stone
                    quantity: 10
        7:
            name: candle_factory
            gold: 70
            resources:
                24:
                    name: wood
                    quantity: 50
        8:
            name: winery
            gold: 50
            resources:
                24:
                    name: wood
                    quantity: 50
                23:
                    name: stone
                    quantity: 5
        9:
            name: beehives
            gold: 50
            resources:
                24:
                    name: wood
                    quantity: 50
        10:
            name: farm
            gold: 40
            resources:
                24:
                    name: wood
                    quantity: 50
        11:
            name: grapevine
            gold: 50
            resources:
                24:
                    name: wood
                    quantity: 50
        12:
            name: wheat_field
            gold: 40
            resources:
                24:
                    name: wood
                    quantity: 30
        13:
            name: mill
            gold: 60
            resources:
                24:
                    name: wood
                    quantity: 70
        14:
            name: iron_mine
            gold: 50
            resources:
                24:
                    name: wood
                    quantity: 50
        15:
            name: stable
            gold: 50
            resources:
                24:
                    name: wood
                    quantity: 200
                23:
                    name: stone
                    quantity: 10
        16:
            name: forge
            gold: 50
            resources:
                24:
                    name: wood
                    quantity: 50
                23:
                    name: stone
                    quantity: 5
        17:
            name: armory
            gold: 50
            resources:
                24:
                    name: wood
                    quantity: 50
                23:
                    name: stone
                    quantity: 5
        18:
            name: apothecary
            gold: 50
            resources:
                24:
                    name: wood
                    quantity: 50
        19:
            name: stone_quarry
            gold: 50
            resources:
                24:
                    name: wood
                    quantity: 50
        20:
            name: lamberjack_camp
            gold: 50
            resources:
                24:
                    name: wood
                    quantity: 50
        21:
            name: barrack
            gold: 70
            resources:
                24:
                    name: wood
                    quantity: 70
                23:
                    name: stone
                    quantity: 15
        22:
            name: archery
            gold: 100
            resources:
                24:
                    name: wood
                    quantity: 100
                23:
                    name: stone
                    quantity: 10
        23:
            name: port
            gold: 100
            resources:
                24:
                    name: wood
                    quantity: 100
                23:
                    name: stone
                    quantity: 10