# Rules for increase level building
parameters:
    buildings_rules:
        hunting_lodge:
            id: 1
            gold: 50
            resources:
                wood:
                    id: 24
                    quantity: 50
        vegetable_garden:
            id: 2
            gold: 50
            resources:
                wood:
                    id: 24
                    quantity: 60
        plantation:
            id: 3
            gold: 70
            resources:
                wood:
                    id: 24
                    quantity: 60
        bakery:
            id: 4
            gold: 50
            resources:
                wood:
                    id: 24
                    quantity: 50
        dairy_farm:
            id: 5
            gold: 50
            resources:
                wood:
                    id: 24
                    quantity: 60
        cheese_factory:
            id: 6
            gold: 50
            resources:
                wood:
                    id: 24
                    quantity: 50
                stone:
                    id: 23
                    quantity: 10
        candle_factory:
            id: 7
            gold: 70
            resources:
                wood:
                    id: 24
                    quantity: 50
        winery:
            id: 8
            gold: 50
            resources:
                wood:
                    id: 24
                    quantity: 50
                stone:
                    id: 23
                    quantity: 5
        beehives:
            id: 9
            gold: 50
            resources:
                wood:
                    id: 24
                    quantity: 50
        farm:
            id: 10
            gold: 40
            resources:
                wood:
                  id: 24
                  quantity: 50
        grapevine:
            id: 11
            gold: 50
            resources:
                wood:
                    id: 24
                    quantity: 50
        wheat_field:
            id: 12
            gold: 40
            resources:
                wood:
                    id: 24
                    quantity: 30
        mill:
            id: 13
            gold: 60
            resources:
                wood:
                    id: 24
                    quantity: 70
        iron_mine:
            id: 14
            gold: 50
            resources:
                wood:
                    id: 24
                    quantity: 50
        stable:
            id: 15
            gold: 50
            resources:
                wood:
                    id: 24
                    quantity: 200
                stone:
                    id: 23
                    quantity: 10
        forge:
            id: 16
            gold: 50
            resources:
                wood:
                    id: 24
                    quantity: 50
                stone:
                    id: 23
                    quantity: 5
        armory:
            id: 17
            gold: 50
            resources:
                wood:
                    id: 24
                    quantity: 50
                stone:
                    id: 23
                    quantity: 5
        apothecary:
            id: 18
            gold: 50
            resources:
                wood:
                    id: 24
                    quantity: 50
        stone_quarry:
            id: 19
            gold: 50
            resources:
                wood:
                    id: 24
                    quantity: 50
        lamberjack_camp:
            id: 20
            gold: 50
            resources:
                wood:
                    id: 24
                    quantity: 50
        barrack:
            id: 21
            gold: 70
            resources:
                wood:
                    id: 24
                    quantity: 70
                stone:
                    id: 23
                    quantity: 15
        archery:
            id: 22
            gold: 100
            resources:
                wood:
                    id: 24
                    quantity: 100
                stone:
                    id: 23
                    quantity: 10
        port:
            id: 23
            gold: 100
            resources:
                wood:
                    id: 24
                    quantity: 100
                stone:
                    id: 23
                    quantity: 10